# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aytDenemeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(367, 360)
        self.spinBoxMatematik = QtWidgets.QSpinBox(Dialog)
        self.spinBoxMatematik.setGeometry(QtCore.QRect(110, 60, 241, 24))
        self.spinBoxMatematik.setObjectName("spinBoxMatematik")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.label_4.setObjectName("label_4")
        self.pushButtonTamam = QtWidgets.QPushButton(Dialog)
        self.pushButtonTamam.setGeometry(QtCore.QRect(190, 300, 151, 41))
        self.pushButtonTamam.setObjectName("pushButtonTamam")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 91, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 91, 21))
        self.label_6.setObjectName("label_6")
        self.spinBoxFizik = QtWidgets.QSpinBox(Dialog)
        self.spinBoxFizik.setGeometry(QtCore.QRect(110, 160, 241, 24))
        self.spinBoxFizik.setObjectName("spinBoxFizik")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label.setObjectName("label")
        self.spinBoxEdebiyat = QtWidgets.QSpinBox(Dialog)
        self.spinBoxEdebiyat.setGeometry(QtCore.QRect(110, 20, 241, 24))
        self.spinBoxEdebiyat.setObjectName("spinBoxEdebiyat")
        self.spinBoxSosyal = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSosyal.setGeometry(QtCore.QRect(110, 110, 241, 24))
        self.spinBoxSosyal.setObjectName("spinBoxSosyal")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.label_2.setObjectName("label_2")
        self.spinBoxKimya = QtWidgets.QSpinBox(Dialog)
        self.spinBoxKimya.setGeometry(QtCore.QRect(110, 210, 241, 24))
        self.spinBoxKimya.setObjectName("spinBoxKimya")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 91, 21))
        self.label_3.setObjectName("label_3")
        self.spinBoxBiyoloji = QtWidgets.QSpinBox(Dialog)
        self.spinBoxBiyoloji.setGeometry(QtCore.QRect(110, 260, 241, 24))
        self.spinBoxBiyoloji.setObjectName("spinBoxBiyoloji")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "FİZİK :"))
        self.pushButtonTamam.setText(_translate("Dialog", "TAMAM"))
        self.label_5.setText(_translate("Dialog", "KİMYA :"))
        self.label_6.setText(_translate("Dialog", "BİYOLOJİ :"))
        self.label.setText(_translate("Dialog", "EDEBİYAT :"))
        self.label_2.setText(_translate("Dialog", "MATEMATİK :"))
        self.label_3.setText(_translate("Dialog", "SOSYAL :"))
