# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 510)
        self.listWidgetOgrenciler = QtWidgets.QListWidget(Dialog)
        self.listWidgetOgrenciler.setGeometry(QtCore.QRect(0, 0, 411, 471))
        self.listWidgetOgrenciler.setObjectName("listWidgetOgrenciler")
        self.pushButtonEkle = QtWidgets.QPushButton(Dialog)
        self.pushButtonEkle.setGeometry(QtCore.QRect(0, 470, 111, 41))
        self.pushButtonEkle.setObjectName("pushButtonEkle")
        self.pushButtonSil = QtWidgets.QPushButton(Dialog)
        self.pushButtonSil.setGeometry(QtCore.QRect(110, 470, 111, 41))
        self.pushButtonSil.setObjectName("pushButtonSil")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonEkle.setText(_translate("Dialog", "EKLE"))
        self.pushButtonSil.setText(_translate("Dialog", "SİL"))
