# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ogrenciEkleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(364, 195)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditIsim = QtWidgets.QLineEdit(Dialog)
        self.lineEditIsim.setGeometry(QtCore.QRect(170, 30, 171, 31))
        self.lineEditIsim.setObjectName("lineEditIsim")
        self.lineEditSoyIsim = QtWidgets.QLineEdit(Dialog)
        self.lineEditSoyIsim.setGeometry(QtCore.QRect(170, 80, 171, 31))
        self.lineEditSoyIsim.setObjectName("lineEditSoyIsim")
        self.pushButtonTamam = QtWidgets.QPushButton(Dialog)
        self.pushButtonTamam.setGeometry(QtCore.QRect(230, 130, 113, 32))
        self.pushButtonTamam.setObjectName("pushButtonTamam")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "İSİM:"))
        self.label_2.setText(_translate("Dialog", "SOYİSİM:"))
        self.pushButtonTamam.setText(_translate("Dialog", "TAMAM"))
