# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tytDenemeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 340)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label.setObjectName("label")
        self.spinBoxTurkce = QtWidgets.QSpinBox(Dialog)
        self.spinBoxTurkce.setGeometry(QtCore.QRect(100, 10, 241, 24))
        self.spinBoxTurkce.setObjectName("spinBoxTurkce")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_2.setObjectName("label_2")
        self.spinBoxMatematik = QtWidgets.QSpinBox(Dialog)
        self.spinBoxMatematik.setGeometry(QtCore.QRect(100, 50, 241, 24))
        self.spinBoxMatematik.setObjectName("spinBoxMatematik")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.label_3.setObjectName("label_3")
        self.spinBoxSosyal = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSosyal.setGeometry(QtCore.QRect(100, 100, 241, 24))
        self.spinBoxSosyal.setObjectName("spinBoxSosyal")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 91, 21))
        self.label_4.setObjectName("label_4")
        self.spinBoxFizik = QtWidgets.QSpinBox(Dialog)
        self.spinBoxFizik.setGeometry(QtCore.QRect(100, 150, 241, 24))
        self.spinBoxFizik.setObjectName("spinBoxFizik")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 91, 21))
        self.label_5.setObjectName("label_5")
        self.spinBoxKimya = QtWidgets.QSpinBox(Dialog)
        self.spinBoxKimya.setGeometry(QtCore.QRect(100, 200, 241, 24))
        self.spinBoxKimya.setObjectName("spinBoxKimya")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 91, 21))
        self.label_6.setObjectName("label_6")
        self.spinBoxBiyoloji = QtWidgets.QSpinBox(Dialog)
        self.spinBoxBiyoloji.setGeometry(QtCore.QRect(100, 250, 241, 24))
        self.spinBoxBiyoloji.setObjectName("spinBoxBiyoloji")
        self.pushButtonTamam = QtWidgets.QPushButton(Dialog)
        self.pushButtonTamam.setGeometry(QtCore.QRect(180, 290, 151, 41))
        self.pushButtonTamam.setObjectName("pushButtonTamam")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TÜRKÇE :"))
        self.label_2.setText(_translate("Dialog", "MATEMATİK :"))
        self.label_3.setText(_translate("Dialog", "SOSYAL :"))
        self.label_4.setText(_translate("Dialog", "FİZİK :"))
        self.label_5.setText(_translate("Dialog", "KİMYA :"))
        self.label_6.setText(_translate("Dialog", "BİYOLOJİ :"))
        self.pushButtonTamam.setText(_translate("Dialog", "TAMAM"))
